brian_laptop:
  data_path: /Users/bcarte18/Documents/Learning/personal_git/push-over-pandas_pycon-ireland-19/data/
data:
  nyc_taxi_2015_hdfs: nyc_taxi2015.hdf5
  nyc_taxi_all_hdfs: nyc_taxi_all.hdf5
  dc_taxi_2017: taxi_final.csv
  dc_taxi_2017_quad: taxi_final_quadruple.csv
  iris_csv: iris.csv
  iris_parquet: iris.parquet
  iris_hdf : iris.hdf5
  kaggle_nyc_train: ny_city_kaggle_fare_prediction_train.csv
  kaggle_nyc: ny_city_kaggle_fare_prediction_test.csv
  kaggle_nyc_test: ny_city_kaggle_fare_prediction_train_sample_10000.csv
  metadata: meta_data.json
  nyc_yellow_trip_csv: yellow_tripdata_2010-06.csv
  nyc_yellow_trip_parquet_snappy: yellow_tripdata_2010-06_snappy.parquet
  nyc_yellow_trip_parquet_gzip: yellow_tripdata_2010-06_gzip.parquet
  nyc_yellow_trip_hdf: yellow_tripdata_2010-06.hdf
  nyc_yellow_trip_hdf5: yellow_tripdata_2010-06.hdf5
contants:
  mb_div: 1000000
  gb_div: 1000000000
